config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  as :user do
    unauthenticated { root 'users/sessions#new' }
    authenticated { root 'targets#index' }
  end

  devise_for :users, controllers: {
    confirmations:  'users/confirmations',
    passwords:      'users/passwords',
    registrations:  'users/registrations',
    sessions:       'users/sessions'
  }, skip: %i[registrations]

  devise_scope :user do
    get   '/users/sign_up', to: 'users/registrations#new',    as: :new_user_registration
    patch '/users',         to: 'users/registrations#update', as: :user_registration
    post  '/users',         to: 'users/registrations#create', as: nil
  end

  resources :targets, only: %i[index create destroy], format: false do
    get :topic_icon, on: :collection
  end

  resources :chats, only: %i[create] do
    resources :messages, only: [:create]
  end
end

app/models/target.rb
# == Schema Information
#
# Table name: targets
#
#  id        :bigint(8)        not null, primary key
#  title     :string           not null
#  topic     :string           not null
#  size      :integer          not null
#  latitude  :decimal(, )      not null
#  longitude :decimal(, )      not null
#  user_id   :bigint(8)
#

# Class to register users targets in map
class Target < ActiveRecord::Base
  MIN_SIZE = 50
  MAX_SIZE = 500
  LIMIT = 5
  TOPICS = [
    { title: I18n.t(:topics_sports),    icon: 'sports-icon.png' },
    { title: I18n.t(:topics_travel),    icon: 'travel-icon.png' },
    { title: I18n.t(:topics_politics),  icon: 'politics-icon.png' },
    { title: I18n.t(:topics_arts),      icon: 'art-icon.png' },
    { title: I18n.t(:topics_dating),    icon: 'dating-icon.png' },
    { title: I18n.t(:topics_music),     icon: 'music-icon.png' },
    { title: I18n.t(:topics_movies),    icon: 'movies-icon.png' },
    { title: I18n.t(:topics_series),    icon: 'series-icon.png' },
    { title: I18n.t(:topics_food),      icon: 'food-icon.png' }
  ].freeze

  belongs_to :user
  delegate :name, :id, to: :user, prefix: true

  validates :title, :topic, :latitude, :longitude, presence: true
  validates :size,
            presence: true,
            numericality: { greater_than_or_equal_to: MIN_SIZE, less_than_or_equal_to: MAX_SIZE }
  validate :validate_targets_limit

  acts_as_mappable default_units:       :meters,
                   default_formula:     :flat,
                   distance_field_name: :distance,
                   lat_column_name:     :latitude,
                   lng_column_name:     :longitude

  def compatible_targets
    TargetMatcherService.matches_for(self)
  end

  private

  def validate_targets_limit
    errors.add(:user_limit, 'reached user limit') if user.targets.count >= LIMIT
  end
end

app/controllers/targets_controller.rb
class TargetsController < ApplicationController
  helper_method :topics
  before_action :authenticate_user!

  def index
    @targets = current_user.targets
    @compatibles = compatible_targets
  end

  def create
    @target = Target.new(target_params)
    @target.user = current_user
    if @target.save
      render json: { target: @target }, status: :ok
    else
      render json: { errors: @target.errors }, status: :unprocessable_entity
    end
  end

  def destroy
    target = Target.find(params[:id])
    if target.destroy
      render json: { message: I18n.t(:alert_success_target_deleted) }, status: :ok
    else
      render json: { errors: I18n.t(:alert_error_target_cant_be_deleted) },
             status: :unprocessable_entity
    end
  end

  def topic_icon
    topic = Target::TOPICS.detect { |top| top[:title] == params[:topic] }
    render json: { icon: topic[:icon] }, status: :ok
  end

  private

  def target_params
    params.require(:target).permit(:title, :topic, :size, :latitude, :longitude)
  end

  def topics
    @topics = Target::TOPICS.map { |topic| [topic[:title], topic[:title]] }.to_h
  end

  def compatible_targets
    TargetMatcherService.matches_for_all_targets(@targets)
  end
end

app/views/targets/_compatible_targets.html.erb
<h4 class="sidebar-subtitle"><%=I18n.t(:title_compatible_targets)%></h4>
<% if compatibles.any? %>
  <table class="table">
    <tbody>
      <% compatibles.each do |target| %>
        <tr>
          <td><%= image_tag(get_topic_icon(target.topic), size: '24x24', class: 'sidebar-compatibles-icon') %></td>
          <td>
            <span class="sidebar-compatibles title"><%= target.title %></span><br>
            <span class="sidebar-compatibles">
              <%= image_tag("user-default-avatar.png", size: '20x20') %> <%= target.user_name %>
            </span>
          </td>
          <td>
            <%= link_to '<i class="fa fa-envelope"></i>'.html_safe, chats_path(user_id: target.user_id), 
                method: :post, remote: true, name: "btn_open_chat", class: 'sidebar-compatibles-envelope' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <br>
  <h4 class="sidebar-subtitle"><%=I18n.t(:paragraph_no_compatible_targets)%></h4>
<% end %>

app/views/targets/_new_target.html.erb
<%= form_for :target, method: :post, remote: true, url: { action: :create }, html: { id: "form_new_target", autocomplete: "off" } do |form| %>
  <h4 class="sidebar-subtitle"><%=I18n.t(:title_create_new_target)%></h4>

  <%= form.label :title, I18n.t(:label_target_title), class: 'sidebar-input-label' %><br>
  <%= form.text_field :title, class: 'sidebar-input-text' %><br>

  <%= form.label :size, I18n.t(:label_target_size), class: 'sidebar-input-label' %><br>
  <%= form.text_field :size, class: 'sidebar-input-text' %><br>

  <%= form.label :topic, I18n.t(:label_target_topic), class: 'sidebar-input-label' %><br>
  <%= select("target", "topic", options_for_select(topics, target ? target.topic : nil), { include_blank: I18n.t(:topics_blank_option) }, class: 'sidebar-input-text') %><br>

  <%= form.hidden_field :latitude %>
  <%= form.hidden_field :longitude %>

  <%= button_tag I18n.t(:btn_cancel), type: :button, class: 'sidebar-form-button secondary', onclick: 'showTargetMatchesSection()' %>
  <%= form.submit I18n.t(:btn_save_target), class: 'sidebar-form-button primary' %>
<% end %>

app/views/targets/_target_modal.erb
<div class="modal fade" id="targetModal" tabindex="-1" role="dialog" aria-labelledby="targetModal" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content text-wrapper">
      <div class="modal-header">
        <h5 class="modal-title"><%=I18n.t(:title_target_data)%></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <table class="table">
          <tbody>
            <tr>
              <td class="details-concept"><%=I18n.t(:details_target_title)%>:</td>
              <td class="details-value" id="targetTitle"></td>
            </tr>
            <tr>
              <td class="details-concept"><%=I18n.t(:details_target_topic)%>:</td>
              <td class="details-value" id="targetTopic"></td>
            </tr>
            <tr>
              <td class="details-concept"><%=I18n.t(:details_target_size)%>:</td>
              <td class="details-value" id="targetSize"></td>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="modal-footer">
        <button type="button" class="modal-button secondary" data-dismiss="modal"><%=I18n.t(:btn_close)%></button>
        <button type="button" class="modal-button warning" onclick="deleteTarget()"><%=I18n.t(:btn_delete_target)%></button>
      </div>
    </div>
  </div>
</div>

app/views/targets/index.html.erb
<div id="sidebar" class="text-wrapper col-md-3">
  <%= render "shared/sidebar", target: @target, compatibles: @compatibles %>
</div>
<div id="content" class="col-md-9">
  <%= render "shared/map", targets: @targets %>
</div>
<%= render "targets/target_modal" %>

<script>
  $(document).ready(function() {
    var formNewTarget = $('#form_new_target');
    var btnOpenChat = $('a[name=btn_open_chat]');

    formNewTarget.on('ajax:success', handleTargetCreated);
    formNewTarget.on('ajax:error', showErrorAlert);
    
    btnOpenChat.on('ajax:success', handleOpenChat);

    function handleTargetCreated(event) {
      toastr.success('<%=I18n.t(:alert_success_target_created)%>');
      var target = event.detail[0]['target'];
      formNewTarget.trigger('reset');
      hideSelectedMarker();
      addTargetCircle(target);
      addTargetMarker(target);
      showTargetMatchesSection();
    }

    function showErrorAlert(event) {
      var errors = event.detail[0]['errors'];
      if (errors.latitude) {
        toastr.warning('<%=I18n.t(:alert_error_target_not_set)%>');
      } else if (errors.user_limit) {
        toastr.warning('<%=I18n.t(:alert_error_target_limit, limit: Target::LIMIT)%>');
      } else if (errors.size) {
        toastr.warning('<%=I18n.t(:alert_error_target_size_invalid)%>');
      } else {
        toastr.warning('<%=I18n.t(:alert_error_target_data_incomplete)%>');
      }
    }

    function handleOpenChat(event) {
      var chat_partial = event.detail[0]['chat_partial'];
      showChatSection(chat_partial);
    }
  });
</script>